#include "header.h"

/**
 * exitr - exits the shell
 * @en: environment variables
 * @bf: buffer generated by getline
 * @ar: array generated by breaking the line into words
 * @h: pointer to first element of PATH linked list
 * @er: exit status of function
 * @ag: may set alternate exit status
 * @nm: number for free_env function
 *
 * Return: void
 */
void exitr(char *ag, char **en, char *bf, char **ar, list_t *h, int er, int nm)
{
	if (ag != NULL)
	{
		er = atoi(ag);
		if (er < 0)
		{
			dprintf(2, "./hsh: 1: exit: Illegal number: %s\n", ag);
			exit(2);
		}
		if (er == 0 && ag[0] != '0')
		{
			dprintf(2, "./hsh: 1: exit: Illegal number: %s\n", ag);
			exit(2);
		}
	}
	free(bf);
	free_array(ar);
	free_env(en, nm);
	free_list(h);
	if (er == 0 && ag != NULL && er == 0)
		er = errno;
	exit(er);
}
